site_name: http.video
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    #- toc.integrate
    - toc.follow
    - toc:
      permalink: true
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
    - material.extensions.emoji.twemoji 
    - material.extensions.emoji.to_svg
    - attr_list
    - pymdownx.highlight:
        anchor_linenums: true
    - pymdownx.inlinehilite
    - pymdownx.snippets
    - admonition
    - pymdownx.arithmatex:
        generic: true
    - footnotes
    - pymdownx.details
    - pymdownx.superfences
    - pymdownx.mark
  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline 
        name: Switch to dark mode
      primary: deep-orange
      accent: purple 
    - scheme: slate 
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode    
      primary: deep-orange
      accent: lime

plugins:
  - social
  - search
  - autorefs
  - awesome-pages

extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/jamiefletchertv
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/jamiefletchertv/
  extra:
  analytics:
    provider: google
    property: G-SMX39Z84J3

nav:
    - index.md    
    ## Disable Working pages from navigation bar
    #- media-analysis-conformance.md
    #- media-playback.md
    #- media-prepartation.md
    #- media-standards.md
    #- players.md

copyright: |
  &copy; 2024 <a href="https://jamiefletcher.dev/http.video"  target="_blank" rel="noopener">Jamie Fletcher</a>