site_name: http.video
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    #- toc.follow
    - toc:
      permalink: true
      depth: 3
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
    - material.extensions.emoji.twemoji 
    - material.extensions.emoji.to_svg
    - attr_list
    - pymdownx.highlight:
        anchor_linenums: true
    - pymdownx.arithmatex:
        generic: true
    - pymdownx.details
    - pymdownx.highlight
    - pymdownx.inlinehilite
    - pymdownx.mark
    - pymdownx.snippets
    - pymdownx.superfences
    - admonition

    - footnotes



  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline 
        name: Switch to dark mode
      primary: deep-orange
      accent: purple 
    - scheme: slate 
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode    
      primary: deep-orange
      accent: lime

plugins:
  - social
  - search
  - autorefs
  - awesome-pages
  - macros

nav:
    - Home: index.md    
    - Media Preparation:
        - Encoding: media-preparation-encoding.md
        - Packaging: media-preparation-packaging.md
        - Encryption: media-preparation-encryption.md
    - media-analysis-and-conformance.md
    - media-blogs-news-insights.md
    - media-education.md
    - media-playback.md
    - media-preparation.md
    - media-standards.md
    - media-test-streams.md
    #- players.md

copyright: |
  &copy; 2024 <a href="https://jamiefletcher.dev/http.video"  target="_blank" rel="noopener">Jamie Fletcher</a>

extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/jamiefletchertv
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/jamiefletchertv/
  analytics:
    provider: google
    property: G-SMX39Z84J3
  
  bento4: https://github.com/axiomatic-systems/Bento4
  eventmessagetrack: https://github.com/unifiedstreaming/event-message-track
  ffmpeg: https://github.com/FFmpeg/FFmpeg
  fmp4ingest: https://github.com/unifiedstreaming/fmp4-ingest
  gpac: https://wiki.gpac.io/
  pycpix: https://github.com/unifiedstreaming/pycpix
  shaka_packager: https://github.com/shaka-project/shaka-packager
  akamai_stream_validator: https://players.akamai.com/stream-validator
  apple_hls_tools: https://developer.apple.com/documentation/http-live-streaming/using-apple-s-http-live-streaming-hls-tools
  aximon_drm_decoders: https://tools.axinom.com/
  dashif_conformance: https://conformance.dashif.org/
  dashif_content_protection_list: https://dashif.org/identifiers/content_protection/
  dolby_stream_validator: https://ott.dolby.com/ondelkits_dev/streamvalidator/start_here.html
  epic_labs_video_comparator: https://github.com/epiclabs-io/epic-video-comparator
  google_dai_sdk_for_html5_video_suite_inspector: https://googleads.github.io/googleads-ima-html5-dai/vsi/
  gpac_mp4box: https://github.com/gpac/gpac/wiki/mp4box
  m2amedia_scte35_dump_for_mpegts: https://github.com/m2amedia/scte35dump
  middleman_scte35_104_parser: https://tools.middleman.tv/scte35-parser
  threefive_scte35: https://github.com/futzu/scte-35_threefive
  thumbcoil_video_inspector: https://thumb.co.il/
  unified_streaming_validator: https://validator.unified-streaming.com/
  akamai_players: https://players.akamai.com/players
  chrome_media_internals: chrome://media-internals
  dash_js: https://github.com/dash-industry-forum/dash.js
  eyevinn_stream_coruptor: https://github.com/eyevinn/streaming-onboarding/blob/master/stream-corruptor.md
  man_in_the_middle_proxy: https://github.com/mitmproxy/mitmproxy
  shaka_player: https://github.com/shaka-project/shaka-player
  apple_reference_streams: https://developer.apple.com/streaming/examples/
  bbc_r_d_mpeg_dash_test_media: http://rdmedia.bbc.co.uk/
  bitmovin_test_stream: https://bitmovin.com/demos/stream-test
  dash_if_test_assets_database: https://testassets.dashif.org/#testvector/list
  dash_sequences_gpac_wiki: https://github.com/gpac/gpac/wiki/dash-sequences
  eyevinn_streaming_samples: https://github.com/eyevinn/http-streaming-samples
  mpeg_dash_sample_content_bento4: http://www.bento4.com/developers/dash/dash-sample-content/
  mux_hls_streams: https://test-streams.mux.dev/
  rufael_demo_streams: https://dvb-2017-dm.s3.eu-central-1.amazonaws.com/overview.html
  unified_streaming_demos: https://demo.unified-streaming.com_
  unified_streaming_features_page: https://demo.unified-streaming.com/k8s/features/stable/#!/mpd
  advanced_television: https://advanced-television.com/
  amagi_blog: https://www.amagi.com/resources/
  anevia_blog: https://anevia.com/blog/
  aws_developer_forums: https://forums.aws.amazon.com/category.jspa?categoryID=43
  aws_elemental_live_knowledge_centre: https://repost.aws/tags/TAdvB1VHw2SDinN3XY4E6oJQ/aws-elemental-live
  aws_medialive_knowledge_centre: https://repost.aws/tags/TAQT5TNwtgSqeM9NCSKfOJPQ/aws-elemental-medialive
  aws_mediatailor_knowledge_centre: https://repost.aws/tags/TAtkvXWoCvTpe77g9M3Tuv_Q/aws-elemental-mediatailor
  bbc_blogs_technology_creativity: https://www.bbc.co.uk/blogs/internet
  bbc_design_engineering_medium: https://medium.com/bbc-design-engineering
  bbc_iplayer_design_engineering_medium: https://medium.com/bbc-design-engineering/iplayer/home
  bitmovin_blog: https://bitmovin.com/blog/
  streaming_learning_center_blog: https://streaminglearningcenter.com/blog
  broadcast_now: https://www.broadcastnow.co.uk/tech
  euro_streaming_media: http://europe.streamingmedia.com/
  eyevinn_technology_medium: https://medium.com/@eyevinntechnology
  fast_services_observer: https://observer.com/2024/04/paramount-streaming-ceo-tom-ryan-speaks-growth-of-fast-services-in-streaming/
  future_of_tv_archives_digiday: https://digiday.com/future-of-tv/
  vertical_integration_us_tv_movie_media: https://imgur.com/gallery/dhrhkaZ
  haivision_blog: https://www.haivision.com/products/kb-series/
  iabm_news: https://www.theiabm.org/newslist/?news_type%5B%5D=Technology+News&topline_tag=
  mpeg_news: https://mpeg.chiariglione.org/news
  mux_blog: https://mux.com/blog/
  netflix_techblog: https://netflixtechblog.com/
  sofia_digital_blog: https://sofiadigital.com/blog/
  sportspro_media: http://www.sportspromedia.com/
  streaming_forum: http://www.streaming-forum.com/2019/LatestNewsArchive.aspx
  streaming_media: https://www.streamingmedia.com/
  streamroot_blog: https://blog.streamroot.io/
  televisual: http://www.televisual.com/news.html
  generative_ai_tools_datacamp: https://www.datacamp.com/cheat-sheet/the-generative-ai-tools-landscape
  global_media_landscape: https://www.gwi.com/reports/global-media-landscape
  thedrmblog: https://go.buydrm.com/thedrmblog
  theoplayer_blog: https://www.theoplayer.com/blog
  tvbeurope: https://www.tvbeurope.com/
  tvtechnology: https://www.tvtechnology.com/
  video_delivery_landscape: https://tinuiti.com/blog/ott-ads/video-delivery-landscape/
  vrt_digital_products_medium: https://medium.com/vrt-digital-studio/
  wowza_blog: https://www.wowza.com/blog/category/blog
  yospace_blog: http://www.yospace.com/category/blog/
  how_video_works: https://howvideo.works/
  leandro_moreira_introduction_digital_video: https://github.com/leandromoreira/digital_video_introduction
  streaming_learning_center: https://streaminglearningcenter.com/
  video_streaming_glossary_explained: https://tinuiti.com/blog/ott-ads/video-streaming-glossary/
  dash_if_interoperability_guidelines_v5: https://dashif.org/guidelines/iop-v5/
  dash_if_live_media_ingest_protocol: https://dashif-documents.azurewebsites.net/ingest/master/dash-if-ingest.html
  microsoft_azure_smooth_streaming_live_ingest_specification: https://learn.microsoft.com/en-us/previous-versions/media-services/previous/media-services-fmp4-live-ingest-overview
  http_live_streaming_overview_hls: https://developer.apple.com/documentation/http-live-streaming
  cta_5005_a_dash_hls_interoperability_specification: https://cdn.cta.tech/cta/media/media/resources/standards/cta-5005-a-final.pdf
  dvb_a178_3_targeted_advertisement_bluebook_for_dvb_dash: https://dvb.org/?standard=dynamic-substitution-of-content-in-linear-broadcast-part-3-carriage-and-signalling-of-placement-opportunity-information-in-dvb-dash
  3gpp: https://www.3gpp.org/
  alliance_for_open_media: https://aomedia.org/
  atsc: https://www.atsc.org/
  cp2pa: https://c2pa.org/
  cta_wave: https://github.com/cta-wave
  dash_if: https://dashif.org/
  dvb: https://dvb.org/
  hbbtv: https://www.hbbtv.org/
  iso: https://www.iso.org/home.html
  itu: https://www.itu.int/en/Pages/default.aspx
  mp4_registration_authority: https://mp4ra.org/
  mpeg: https://www.mpeg.org/about-mpeg/
  scte: https://www.scte.org/
  smpte: https://www.smpte.org/
  svta: https://www.svta.org/
  w3c: https://www.w3.org/